// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Custom lock function that bypasses navigator.locks to prevent AbortError in dev mode
// Must be generic to match Supabase's LockFunc type
const customLock = async <R,>(
  _name: string, 
  _acquireTimeout: number, 
  acquire: () => Promise<R>
): Promise<R> => {
  // Bypass navigator.locks - just call acquire directly
  return acquire();
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: false,
    // Use custom lock to prevent AbortError from navigator.locks
    lock: customLock,
  },
});